# Generated by Django 6.0.3 on 2026-04-05 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorie',
            name='description',
        ),
        migrations.AlterField(
            model_name='categorie',
            name='nom',
            field=models.CharField(choices=[('Football', 'Football'), ('Basketball', 'Basketball'), ('Tennis', 'Tennis'), ('Volleyball', 'Volleyball'), ('Handball', 'Handball'), ('Judo', 'Judo'), ('Natation', 'Natation'), ('Athlétisme', 'Athlétisme'), ('Boxe', 'Boxe'), ('Cyclisme', 'Cyclisme'), ('Escrime', 'Escrime'), ('Gymnastique', 'Gymnastique'), ('Haltérophilie', 'Haltérophilie'), ('Judo', 'Judo'), ('Lutte', 'Lutte'), ('Natation', 'Natation'), ('Pentathlon', 'Pentathlon'), ('Rugby', 'Rugby'), ('Taekwondo', 'Taekwondo'), ('Tennis', 'Tennis'), ('Tir', 'Tir'), ("Tir à l'arc", "Tir à l'arc"), ('Triathlon', 'Triathlon'), ('Voile', 'Voile'), ('Water-polo', 'Water-polo'), ('Judo', 'Judo'), ('Lutte', 'Lutte'), ('Natation', 'Natation'), ('Pentathlon', 'Pentathlon'), ('Rugby', 'Rugby'), ('Taekwondo', 'Taekwondo'), ('Tennis', 'Tennis'), ('Tir', 'Tir'), ("Tir à l'arc", "Tir à l'arc"), ('Triathlon', 'Triathlon'), ('Voile', 'Voile'), ('Water-polo', 'Water-polo')], max_length=100),
        ),
    ]
