# Generated by Django 6.0.3 on 2026-04-07 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_rename_categorie_categories'),
        ('article', '0005_alter_articles_image'),
    ]

    operations = [
    ]
