# Generated by Django 6.0.3 on 2026-05-11 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_merge_20260407_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='resume',
            field=models.TextField(blank=True, null=True),
        ),
    ]
